version: '3'
services:
  ghost-blog:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=teste
      - database__connection__database=ghost
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: mysql:5.7.40
    environment:
      - MYSQL_ROOT_PASSWORD=teste
    volumes:
      - dados-do-banco:/var/lib/mysql
    networks:
      - my-network
volumes:
  dados-do-banco:

networks:
  my-network:
